version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: wolfeye_mongodb
    restart: always
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

  redis:
    image: redis:latest
    container_name: wolfeye_redis
    restart: always
    ports:
      - "6379:6379"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: wolfeye_backend
    restart: always
    depends_on:
      - mongodb
      - redis
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - MONGO_DB_NAME=wolfeye_plus
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    volumes:
      - ./employee_profiles:/app/employee_profiles
      - ./temp_uploads:/app/temp_uploads
    ports:
      - "8000:8000"

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: wolfeye_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  mongodb_data:
